name: Run emulator

on:
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show files
        run: |
          pwd
          ls -R

      - name: Install dependencies
        run: pip install requests

      - name: Run python emulator.py
        run: python ./emulator.py
